export const JOB_CATEGORIES = [
  "IT - Phần mềm",
  "Marketing / Truyền thông",
  "Kinh doanh / Bán hàng",
  "Kế toán / Kiểm toán",
  "Nhân sự",
  "Thiết kế",
  "Chăm sóc khách hàng",
  "Giáo dục / Đào tạo",
  "Tài chính / Ngân hàng",
  "Khác",
];

export const VIETNAM_PROVINCES = [
  "Hà Nội",
  "Huế",
  "Hải Phòng",
  "Đà Nẵng",
  "Cần Thơ",
  "Thành phố Hồ Chí Minh",

  "Cao Bằng",
  "Tuyên Quang",
  "Lào Cai",
  "Thái Nguyên",
  "Phú Thọ",
  "Bắc Ninh",
  "Hưng Yên",
  "Ninh Bình",
  "Lai Châu",
  "Điện Biên",
  "Sơn La",
  "Lạng Sơn",
  "Quảng Ninh",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Trị",
  "Quảng Ngãi",
  "Gia Lai",
  "Khánh Hòa",
  "Lâm Đồng",
  "Đắk Lắk",
  "Đồng Nai",
  "Tây Ninh",
  "Vĩnh Long",
  "Đồng Tháp",
  "Cà Mau",
  "An Giang",

  "Remote",
];